/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PurchaseCategoryStatistics
    /// </summary>
    [DataContract(Name = "PurchaseCategoryStatistics")]
    public partial class PurchaseCategoryStatistics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseCategoryStatistics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PurchaseCategoryStatistics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseCategoryStatistics" /> class.
        /// </summary>
        /// <param name="items">items (required).</param>
        /// <param name="itemCount">itemCount (required).</param>
        /// <param name="total">total (required).</param>
        public PurchaseCategoryStatistics(List<PurchaseCategoryStatisticsItem> items = default(List<PurchaseCategoryStatisticsItem>), int itemCount = default(int), decimal total = default(decimal))
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for PurchaseCategoryStatistics and cannot be null");
            }
            this.Items = items;
            this.ItemCount = itemCount;
            this.Total = total;
        }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<PurchaseCategoryStatisticsItem> Items { get; set; }

        /// <summary>
        /// Gets or Sets ItemCount
        /// </summary>
        [DataMember(Name = "item_count", IsRequired = true, EmitDefaultValue = true)]
        public int ItemCount { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PurchaseCategoryStatistics {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  ItemCount: ").Append(ItemCount).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
