/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UserTierUpdate
    /// </summary>
    [DataContract(Name = "UserTierUpdate")]
    public partial class UserTierUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTierUpdate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserTierUpdate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserTierUpdate" /> class.
        /// </summary>
        /// <param name="tierUuid">tierUuid (required).</param>
        public UserTierUpdate(Guid? tierUuid = default(Guid?))
        {
            // to ensure "tierUuid" is required (not null)
            if (tierUuid == null)
            {
                throw new ArgumentNullException("tierUuid is a required property for UserTierUpdate and cannot be null");
            }
            this.TierUuid = tierUuid;
        }

        /// <summary>
        /// Gets or Sets TierUuid
        /// </summary>
        [DataMember(Name = "tier_uuid", IsRequired = true, EmitDefaultValue = true)]
        public Guid? TierUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserTierUpdate {\n");
            sb.Append("  TierUuid: ").Append(TierUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
