/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Client.Auth;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupPurchaseCategoryApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Group Purchase Category
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PurchaseCategoryRead</returns>
        PurchaseCategoryRead CreateGroupPurchaseCategory(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0);

        /// <summary>
        /// Create Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PurchaseCategoryRead</returns>
        ApiResponse<PurchaseCategoryRead> CreateGroupPurchaseCategoryWithHttpInfo(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0);
        /// <summary>
        /// Delete Group Purchase Category
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        Message DeleteGroupPurchaseCategory(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0);

        /// <summary>
        /// Delete Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        ApiResponse<Message> DeleteGroupPurchaseCategoryWithHttpInfo(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0);
        /// <summary>
        /// Get Group Purchase Categories
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaginatedListResponsePurchaseCategoryRead</returns>
        PaginatedListResponsePurchaseCategoryRead GetGroupPurchaseCategories(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0);

        /// <summary>
        /// Get Group Purchase Categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaginatedListResponsePurchaseCategoryRead</returns>
        ApiResponse<PaginatedListResponsePurchaseCategoryRead> GetGroupPurchaseCategoriesWithHttpInfo(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0);
        /// <summary>
        /// Update Group Purchase Category
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        Message UpdateGroupPurchaseCategory(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0);

        /// <summary>
        /// Update Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        ApiResponse<Message> UpdateGroupPurchaseCategoryWithHttpInfo(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupPurchaseCategoryApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseCategoryRead</returns>
        System.Threading.Tasks.Task<PurchaseCategoryRead> CreateGroupPurchaseCategoryAsync(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseCategoryRead)</returns>
        System.Threading.Tasks.Task<ApiResponse<PurchaseCategoryRead>> CreateGroupPurchaseCategoryWithHttpInfoAsync(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        System.Threading.Tasks.Task<Message> DeleteGroupPurchaseCategoryAsync(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        System.Threading.Tasks.Task<ApiResponse<Message>> DeleteGroupPurchaseCategoryWithHttpInfoAsync(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Group Purchase Categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaginatedListResponsePurchaseCategoryRead</returns>
        System.Threading.Tasks.Task<PaginatedListResponsePurchaseCategoryRead> GetGroupPurchaseCategoriesAsync(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Group Purchase Categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaginatedListResponsePurchaseCategoryRead)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaginatedListResponsePurchaseCategoryRead>> GetGroupPurchaseCategoriesWithHttpInfoAsync(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        System.Threading.Tasks.Task<Message> UpdateGroupPurchaseCategoryAsync(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update Group Purchase Category
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        System.Threading.Tasks.Task<ApiResponse<Message>> UpdateGroupPurchaseCategoryWithHttpInfoAsync(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupPurchaseCategoryApi : IGroupPurchaseCategoryApiSync, IGroupPurchaseCategoryApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GroupPurchaseCategoryApi : IGroupPurchaseCategoryApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupPurchaseCategoryApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GroupPurchaseCategoryApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupPurchaseCategoryApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GroupPurchaseCategoryApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupPurchaseCategoryApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GroupPurchaseCategoryApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupPurchaseCategoryApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public GroupPurchaseCategoryApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PurchaseCategoryRead</returns>
        public PurchaseCategoryRead CreateGroupPurchaseCategory(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<PurchaseCategoryRead> localVarResponse = CreateGroupPurchaseCategoryWithHttpInfo(groupUuid, purchaseCategoryCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PurchaseCategoryRead</returns>
        public Org.OpenAPITools.Client.ApiResponse<PurchaseCategoryRead> CreateGroupPurchaseCategoryWithHttpInfo(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0)
        {
            // verify the required parameter 'purchaseCategoryCreate' is set
            if (purchaseCategoryCreate == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'purchaseCategoryCreate' when calling GroupPurchaseCategoryApi->CreateGroupPurchaseCategory");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            localVarRequestOptions.Data = purchaseCategoryCreate;

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.CreateGroupPurchaseCategory";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PurchaseCategoryRead>("/api/v1/group/{group_uuid}/purchase-category", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateGroupPurchaseCategory", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseCategoryRead</returns>
        public async System.Threading.Tasks.Task<PurchaseCategoryRead> CreateGroupPurchaseCategoryAsync(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<PurchaseCategoryRead> localVarResponse = await CreateGroupPurchaseCategoryWithHttpInfoAsync(groupUuid, purchaseCategoryCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseCategoryRead)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<PurchaseCategoryRead>> CreateGroupPurchaseCategoryWithHttpInfoAsync(Guid groupUuid, PurchaseCategoryCreate purchaseCategoryCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'purchaseCategoryCreate' is set
            if (purchaseCategoryCreate == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'purchaseCategoryCreate' when calling GroupPurchaseCategoryApi->CreateGroupPurchaseCategory");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            localVarRequestOptions.Data = purchaseCategoryCreate;

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.CreateGroupPurchaseCategory";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PurchaseCategoryRead>("/api/v1/group/{group_uuid}/purchase-category", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateGroupPurchaseCategory", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        public Message DeleteGroupPurchaseCategory(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Message> localVarResponse = DeleteGroupPurchaseCategoryWithHttpInfo(groupUuid, purchaseCategoryUuid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        public Org.OpenAPITools.Client.ApiResponse<Message> DeleteGroupPurchaseCategoryWithHttpInfo(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("purchase_category_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(purchaseCategoryUuid)); // path parameter

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.DeleteGroupPurchaseCategory";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Message>("/api/v1/group/{group_uuid}/purchase-category/{purchase_category_uuid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteGroupPurchaseCategory", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        public async System.Threading.Tasks.Task<Message> DeleteGroupPurchaseCategoryAsync(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Message> localVarResponse = await DeleteGroupPurchaseCategoryWithHttpInfoAsync(groupUuid, purchaseCategoryUuid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to delete.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Message>> DeleteGroupPurchaseCategoryWithHttpInfoAsync(Guid groupUuid, Guid purchaseCategoryUuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("purchase_category_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(purchaseCategoryUuid)); // path parameter

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.DeleteGroupPurchaseCategory";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Message>("/api/v1/group/{group_uuid}/purchase-category/{purchase_category_uuid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteGroupPurchaseCategory", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Group Purchase Categories 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaginatedListResponsePurchaseCategoryRead</returns>
        public PaginatedListResponsePurchaseCategoryRead GetGroupPurchaseCategories(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<PaginatedListResponsePurchaseCategoryRead> localVarResponse = GetGroupPurchaseCategoriesWithHttpInfo(groupUuid, page, itemsPerPage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Group Purchase Categories 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaginatedListResponsePurchaseCategoryRead</returns>
        public Org.OpenAPITools.Client.ApiResponse<PaginatedListResponsePurchaseCategoryRead> GetGroupPurchaseCategoriesWithHttpInfo(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (itemsPerPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "items_per_page", itemsPerPage));
            }

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.GetGroupPurchaseCategories";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PaginatedListResponsePurchaseCategoryRead>("/api/v1/group/{group_uuid}/purchase-category", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGroupPurchaseCategories", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Group Purchase Categories 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaginatedListResponsePurchaseCategoryRead</returns>
        public async System.Threading.Tasks.Task<PaginatedListResponsePurchaseCategoryRead> GetGroupPurchaseCategoriesAsync(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<PaginatedListResponsePurchaseCategoryRead> localVarResponse = await GetGroupPurchaseCategoriesWithHttpInfoAsync(groupUuid, page, itemsPerPage, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Group Purchase Categories 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase categories belong.</param>
        /// <param name="page"> (optional, default to 1)</param>
        /// <param name="itemsPerPage"> (optional, default to 10)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaginatedListResponsePurchaseCategoryRead)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<PaginatedListResponsePurchaseCategoryRead>> GetGroupPurchaseCategoriesWithHttpInfoAsync(Guid groupUuid, int? page = default(int?), int? itemsPerPage = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            if (page != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "page", page));
            }
            if (itemsPerPage != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "items_per_page", itemsPerPage));
            }

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.GetGroupPurchaseCategories";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PaginatedListResponsePurchaseCategoryRead>("/api/v1/group/{group_uuid}/purchase-category", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetGroupPurchaseCategories", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Message</returns>
        public Message UpdateGroupPurchaseCategory(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Message> localVarResponse = UpdateGroupPurchaseCategoryWithHttpInfo(groupUuid, purchaseCategoryUuid, purchaseCategoryUpdate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Message</returns>
        public Org.OpenAPITools.Client.ApiResponse<Message> UpdateGroupPurchaseCategoryWithHttpInfo(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0)
        {
            // verify the required parameter 'purchaseCategoryUpdate' is set
            if (purchaseCategoryUpdate == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'purchaseCategoryUpdate' when calling GroupPurchaseCategoryApi->UpdateGroupPurchaseCategory");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("purchase_category_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(purchaseCategoryUuid)); // path parameter
            localVarRequestOptions.Data = purchaseCategoryUpdate;

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.UpdateGroupPurchaseCategory";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Message>("/api/v1/group/{group_uuid}/purchase-category/{purchase_category_uuid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateGroupPurchaseCategory", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Message</returns>
        public async System.Threading.Tasks.Task<Message> UpdateGroupPurchaseCategoryAsync(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Message> localVarResponse = await UpdateGroupPurchaseCategoryWithHttpInfoAsync(groupUuid, purchaseCategoryUuid, purchaseCategoryUpdate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Group Purchase Category 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupUuid">UUID of the group to which the purchase category belongs.</param>
        /// <param name="purchaseCategoryUuid">UUID of the purchase category to update.</param>
        /// <param name="purchaseCategoryUpdate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Message)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Message>> UpdateGroupPurchaseCategoryWithHttpInfoAsync(Guid groupUuid, Guid purchaseCategoryUuid, PurchaseCategoryUpdate purchaseCategoryUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'purchaseCategoryUpdate' is set
            if (purchaseCategoryUpdate == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'purchaseCategoryUpdate' when calling GroupPurchaseCategoryApi->UpdateGroupPurchaseCategory");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("group_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(groupUuid)); // path parameter
            localVarRequestOptions.PathParameters.Add("purchase_category_uuid", Org.OpenAPITools.Client.ClientUtils.ParameterToString(purchaseCategoryUuid)); // path parameter
            localVarRequestOptions.Data = purchaseCategoryUpdate;

            localVarRequestOptions.Operation = "GroupPurchaseCategoryApi.UpdateGroupPurchaseCategory";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth2PasswordBearer) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<Message>("/api/v1/group/{group_uuid}/purchase-category/{purchase_category_uuid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateGroupPurchaseCategory", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
